platform :ios, '14.0'

# Specify the project path explicitly
project 'OfflineTube.xcodeproj'

target 'OfflineTube' do
  use_frameworks!

  # Pods for OfflineTube
  pod 'GCDWebServer', '~> 3.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end